// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin_feed_min.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "DouyinFeedMin.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - DouyinFeedMinRoot

@implementation DouyinFeedMinRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - DouyinFeedMinRoot_FileDescriptor

static GPBFileDescriptor *DouyinFeedMinRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Feed

@implementation Feed

@dynamic statusCode;
@dynamic statusMsg;
@dynamic cursor;
@dynamic level;
@dynamic hasMore;

typedef struct Feed__storage_ {
  uint32_t _has_storage_[1];
  int32_t statusCode;
  int32_t cursor;
  int32_t level;
  int32_t hasMore;
  NSString *statusMsg;
} Feed__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "statusCode",
        .dataTypeSpecific.clazz = Nil,
        .number = Feed_FieldNumber_StatusCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Feed__storage_, statusCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "statusMsg",
        .dataTypeSpecific.clazz = Nil,
        .number = Feed_FieldNumber_StatusMsg,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Feed__storage_, statusMsg),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "cursor",
        .dataTypeSpecific.clazz = Nil,
        .number = Feed_FieldNumber_Cursor,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Feed__storage_, cursor),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "level",
        .dataTypeSpecific.clazz = Nil,
        .number = Feed_FieldNumber_Level,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Feed__storage_, level),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "hasMore",
        .dataTypeSpecific.clazz = Nil,
        .number = Feed_FieldNumber_HasMore,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Feed__storage_, hasMore),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Feed class]
                                     rootClass:[DouyinFeedMinRoot class]
                                          file:DouyinFeedMinRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Feed__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
